# Generated by Django 4.0.5 on 2022-07-01 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_rename_list_userlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='description',
            field=models.TextField(blank=True, max_length=1250),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='remainderDate',
            field=models.DateField(validators=[django.core.validators.MinValueValidator('2022-07-01')]),
        ),
    ]
