# Generated by Django 4.0.5 on 2022-07-01 13:38

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_alter_userlist_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='remainderDate',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(2022, 7, 1), message='Invalid Date')]),
        ),
    ]
